---

php_executable: "php"

__php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-imap
  - php-fpm
  - php-gd
  - php-ldap
  - php-mbstring
  - php-pdo
  - php-mysql 
  - php-pear
  - php-pecl-apc
  - php-xml
  - php-xmlrpc
  - php-json
  - php-curl
  - php-mcrypt

__php_conf_path: /etc


