---

# Configure php

- include_vars:  php_vars.yml 

- name: Define php_packages
  set_fact: 
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: PHP Install packages 
  yum: name="{{ item  }}"  update_cache=yes state=present
  with_items: php_packages
  notify: restarted httpd 

- name: Check installed version of php
  shell: '{{ php_executable }} -r "echo PHP_VERSION;"'
  register: php_version
  changed_when: false
  always_run: yes

 





