---
- hosts: db
  become: yes
  tasks:
   - name: Install MariaDB
     yum: name=mariadb-server state=present
   - name: Ensure MariaDB is running
     service: name=mariadb state=started enabled=yes 