---
- name: Tomcat app server config
  hosts: appservers
  become: yes
  tasks:
  - name : tomcat | copy local file to remote
    copy : 
       src: sample.war
       dest: /usr/share/tomcat/webapps
       owner: tomcat
       group: tomcat
       mode: u=rwx,g=rx,o=r

  - name : Ensure application is deployed
    stat:
       path : /usr/share/tomcat/webapps/sample

  - name : Check that you can connect before continue playbook
    uri:
       url: http://localhost:8080/sample/index.html
    register: result
    until: result.status == 200
    retries: 10
    delay : 10

  - name : Show result variable
    debug: 
      var: result