---

# install mysql, create db user and permission 

- name: Install Mysql Package
  yum: name={{ item }} state=present
  with_items:
  - mysql-server
  - MySQL-python
# - libselinux-python
# - libemanage-python
  tags:
  - install

#- name: data path permission
#  command: sudo chown -R root:root  {{ mysql_data_dir }} 

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

#- include: update_iptables.yml tags=iptables
- include: init_db.yml 
